---
name: IaC image CI
on:
  push:
    branches:
      - develop

env:
  IMAGE_REPO_NAME: iac-base
  DOCKER_PATH: docker/base
  GCLOUD_LOCATION:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.config.outputs.VERSION }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: google-github-actions/auth@v2
        name: Login Google Cloud
        with:
          credentials_json: ${{ secrets.CI_PRIVATE_KEY }}

      - name: Login to gcr
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Publish image
        run: |
          docker pull nginx
          docker tag nginx europe-west4-docker.pkg.dev/gcloud71:01
          docker push europe-west4-docker.pkg.dev/gcloud71
