---
name: IaC image CI
on:
  push:
    branches:
      - develop

env:
  IMAGE_REPO_NAME: iac-base
  DOCKER_PATH: docker/base

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.config.outputs.VERSION }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: google-github-actions/auth@v1
        name: Login Google Cloud
        with:
          credentials_json: ${{ secrets.CI_PRIVATE_KEY }}
