---
name: IaC image CI

on:
  push:
    branches:
      - develop

env:
  IMAGE_REPO_NAME: iac-base
  DOCKER_PATH: docker/base

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.config.outputs.VERSION }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config version
        id: config
        run: |
          COMMIT_SHA=${{ github.event.pull_request.base.sha }}
          COMMIT_SHA_SHORT=$(echo ${COMMIT_SHA::8})
          IAC_IMAGE_VERSION=$(cat $DOCKER_PATH/.version)
          echo "COMMIT_TAG=$(echo $COMMIT_SHA_SHORT)" >> $GITHUB_ENV
          TERRAFORM_VERSION=$(cat .terraform-version)
          echo "TERRAFORM_VERSION=$(echo $TERRAFORM_VERSION)" >> $GITHUB_ENV
          IMAGE_TAG="${IAC_IMAGE_VERSION}.${GITHUB_RUN_NUMBER}"
          echo "IMAGE_TAG=$(echo IMAGE_TAG)" >> $GITHUB_ENV

      - name: Show config
        id: show-config
        run: |
          echo "COMMIT_TAG=$COMMIT_TAG"
          echo "TERRAFORM_VERSION=$TERRAFORM_VERSION"
          echo "IMAGE_TAG = ${IMAGE_TAG}"
